// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: files.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
insert into files (id, file_name, folder_name)
values ($1, $2, $3)
    returning id, file_name, folder_name
`

type CreateFileParams struct {
	ID         uuid.UUID
	FileName   string
	FolderName string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile, arg.ID, arg.FileName, arg.FolderName)
	var i File
	err := row.Scan(&i.ID, &i.FileName, &i.FolderName)
	return i, err
}
