// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type BlogPost struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	UserID      uuid.UUID
}

type BlogPostFile struct {
	BlogPostID uuid.UUID
	FileID     uuid.UUID
}

type BugReport struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	UserID      uuid.UUID
}

type BugReportFile struct {
	BugReportID uuid.UUID
	FileID      uuid.UUID
}

type File struct {
	ID         uuid.UUID
	FileName   string
	FolderName string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
	Username  string
	Token     string
}
