version: '3.1'

services:
  postgres-db:
    image: 'postgres:latest'
    container_name: scrape-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scrape-db
    ports:
      - "5432:5432"
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=username123
      - MINIO_ROOT_PASSWORD=password123
      - MINIO_DEFAULT_BUCKETS=files

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local