version: '3.1'

services:
  postgres-db:
    image: 'postgres:latest'
    container_name: scrape-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scrape-db
    ports:
      - "5432:5432"

